### ISSUE TITLE
Implementation with API key from Soliscloud

### ISSUE THREAD

**Issue by CyberRagz** [dekinet/MMM-Growatt#1]
My data logger sends data to Soliscloud.com. Is it possible to implement this MM module with the data from that website. There is a repository on github for Soliscloud API. How can the two be merged to implement the module. 
https://github.com/hultenvp/soliscloud_api

**Comment by dekinet** [comment]
Just so I understand, you have a soliscloud logger and as asking how to get MMM-Growatt module to display data from that logger? This module is quite specific to the Growatt API. Several options, I think:

1. You copy the content of this module (MMM-Growatt) and modify as required to communicate with and process data from the soliscloud API; or

2. We (you and/or me) extend MMM-Growatt to include support for data sourced from soliscloud.

3. Look into [MMM-EnergyMonitor](https://github.com/deg0nz/MMM-EnergyMonitor), maybe it can be modified to visualise data from MMM-Growatt in addition to the modules it already supports?

**Comment by CyberRagz** [comment]
Thank you for your prompt response.1. The Soliscloud uses an API, so i gues it may not be possible to use this module.2. Unfortunately i am neither a developer or coder so i would not be of much use to help you develop this module. I can certainly test it.3. EnergyMonitor also may not be useable as it is.
The code in https://github.com/hultenvp/soliscloud_api can be used (i feel) . So if this can be incorporated in your module, i am sure it will work. Just a thought.Thanks
    On Wednesday, 26 April, 2023 at 02:36:00 am IST, dekinet ***@***.***> wrote:  
 
 


Just so I understand, you have a soliscloud logger and as asking how to get MMM-Growatt module to display data from that logger? This module is quite specific to the Growatt API. Several options, I think:
   
   -    
You copy the content of this module (MMM-Growatt) and modify as required to communicate with and process data from the soliscloud API; or

   -    
We (you and/or me) extend MMM-Growatt to include support for data sourced from soliscloud.

   -    
Look into MMM-EnergyMonitor, maybe it can be modified to visualise data from MMM-Growatt in addition to the modules it already supports?

**Comment by dekinet** [comment]
Sorry for the delay. I've had a look at MMM-EnergyMonitor and modifying _it_ to visualise data from other modules does not suit its architecture. It relies on other modules sending it data using a known format -- as such _any_ other module could send data to MMM-EnergyMonitor.

I'd be happy to basically copy the functionality of MMM-Growatt to create a module that communicates with Soliscloud. However, I would need access to a working Soliscloud account to test it. If you're happy to provide with an API key and password, let's take this discussion private and email me: mjlee at mindless dot com

**Comment by dekinet** [comment]
Added https://github.com/dekinet/MMM-Soliscloud
